### ISSUE TITLE
Host Alignment Bot on Digital Ocean

### ISSUE THREAD

**Issue by starSweeper** [starSweeper/AlignmentBot#10]
Many benefits to not having this run on my laptop.

**Comment by KaceyGambill** [comment]
Bot is now being hosted on a server on digital ocean. It's being deployed through Jenkins using pm2. It currently is set up to poll the master branch every 15 minutes for any changes, then build if there are.

**Comment by starSweeper** [comment]
Closing cause Kacey did this months ago :P
